version: "3"
services:
  backend:
    build: .
    ports:
      - "5000:5000"
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    environment:
      - BACKEND_URL=http://backend:5000/chat
    ports:
      - "3000:3000"
    depends_on:
      - backend
