services:
  web:
    dockerfile: Dockerfile
    env:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3
    resources:
      cpu: 1x
      memory: 512MB
    auto_deploy: true
    restart_policy: always
    
  api:
    dockerfile: apps/companion_api/Dockerfile
    env:
      - NODE_ENV=production
      - PORT=8787
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    healthcheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3
    resources:
      cpu: 1x
      memory: 512MB
    auto_deploy: true
    restart_policy: always
    
  python_services:
    build:
      context: .
      dockerfile: Dockerfile.python
    env:
      - FLASK_ENV=production
      - PORT=5000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    healthcheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3
    resources:
      cpu: 0.5x
      memory: 256MB
    auto_deploy: true
    restart_policy: always

networks:
  internal:
    driver: bridge

volumes:
  app_data:
    driver: local