apiVersion: apps/v1
kind: Deployment
metadata:
  name: companion-api-staging
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: companion-api
      env: staging
  template:
    metadata:
      labels:
        app: companion-api
        env: staging
    spec:
      containers:
      - name: companion-api
        image: ghcr.io/rcastrejon91/ai_agents/api:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "staging"
---
apiVersion: v1
kind: Service
metadata:
  name: companion-api-service-staging
  namespace: staging
spec:
  selector:
    app: companion-api
    env: staging
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP