services:
  backend:
    dockerfile: Dockerfile
    env:
      - NODE_ENV=production
      - PORT=5000
      - REDIS_URL=${REDIS_URL}
    healthcheck:
      path: /health
      interval: 30s
      timeout: 100s
      retries: 3
    resources:
      cpu: 1x
      memory: 512MB
    auto_deploy: true
    restart_policy:
      type: ON_FAILURE
      max_retries: 10

  frontend:
    buildCommand: npm run build
    startCommand: npm start
    env:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      path: /
      interval: 30s
      timeout: 30s
      retries: 3
    resources:
      cpu: 1x
      memory: 512MB
    auto_deploy: true

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
