"""
lyra_digest.py  —  Step 3 of the Lyra daily learning pipeline.

Reads /tmp/lyra_processed.json and writes knowledge/YYYY-MM-DD.md.
Each entry in the markdown has: date, domain, title, summary,
key takeaways, significance, and source URL.
"""

import json
import datetime
from pathlib import Path

PROCESSED = Path("/tmp/lyra_processed.json")
TODAY = datetime.date.today().isoformat()
KNOWLEDGE_DIR = Path("knowledge")

DOMAIN_EMOJI = {
    "tech": "💻",
    "research": "🔬",
    "medical": "🧬",
}

DOMAIN_ORDER = ["tech", "research", "medical"]


def render_entry(entry: dict, index: int) -> str:
    emoji = DOMAIN_EMOJI.get(entry["domain"], "📌")
    takeaways = "\n".join(f"  - {t}" for t in entry.get("key_takeaways", []))
    tags = " ".join(f"`{t}`" for t in entry.get("tags", []))
    significance = entry.get("significance", "")

    return f"""### {index}. {emoji} {entry["title"]}

| Field | Value |
|-------|-------|
| **Domain** | {entry["domain"].title()} |
| **Source** | [{entry["source"]}]({entry["url"]}) |
| **Date** | {entry["date"]} |

**Summary**
{entry["summary"]}

**Key Takeaways**
{takeaways}

**Why it matters**
{significance}

**Tags** {tags}

---
"""


def main():
    if not PROCESSED.exists():
        raise FileNotFoundError(f"{PROCESSED} not found — run lyra_process.py first")

    items: list[dict] = json.loads(PROCESSED.read_text())
    if not items:
        print("[lyra_digest] No processed items — nothing to write.")
        return

    KNOWLEDGE_DIR.mkdir(exist_ok=True)
    out_path = KNOWLEDGE_DIR / f"{TODAY}.md"

    # Group by domain in canonical order
    by_domain: dict[str, list[dict]] = {}
    for entry in items:
        by_domain.setdefault(entry["domain"], []).append(entry)

    lines = [
        f"# 🧠 Lyra's Knowledge Digest — {TODAY}\n",
        f"*{len(items)} items processed across {len(by_domain)} domains.*\n\n",
        "## Table of Contents\n",
    ]

    # TOC
    counter = 1
    toc_map: list[tuple[str, dict]] = []
    for domain in DOMAIN_ORDER:
        group = by_domain.get(domain, [])
        if not group:
            continue
        emoji = DOMAIN_EMOJI.get(domain, "📌")
        lines.append(f"- **{emoji} {domain.title()}** ({len(group)} items)\n")
        for entry in group:
            lines.append(f"  - [{counter}. {entry['title'][:70]}](#{counter}-{entry['title'][:30].lower().replace(' ','-').replace('/','-')})\n")
            toc_map.append((domain, entry))
            counter += 1

    lines.append("\n---\n\n")

    # Body — one section per domain
    global_index = 1
    for domain in DOMAIN_ORDER:
        group = by_domain.get(domain, [])
        if not group:
            continue
        emoji = DOMAIN_EMOJI.get(domain, "📌")
        lines.append(f"## {emoji} {domain.title()}\n\n")
        for entry in group:
            lines.append(render_entry(entry, global_index))
            global_index += 1

    # Footer
    lines.append(f"\n---\n*Generated by Lyra on {TODAY}. This file is part of her living knowledge base.*\n")

    out_path.write_text("".join(lines), encoding="utf-8")
    print(f"[lyra_digest] Written → {out_path}  ({len(items)} entries)")


if __name__ == "__main__":
    main()
