apiVersion: apps/v1
kind: Deployment
metadata:
  name: companion-api-production
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: companion-api
      env: production
  template:
    metadata:
      labels:
        app: companion-api
        env: production
    spec:
      containers:
      - name: companion-api
        image: ghcr.io/rcastrejon91/ai_agents/api:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: companion-api-service-production
  namespace: production
spec:
  selector:
    app: companion-api
    env: production
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP