name: CI
on:
  push:
    branches: [ main ]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore: autofix')"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
