name: Deploy Web

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/companion_web   # your web app path

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      # Create .vercel settings from your secrets
      - name: Prepare Vercel project
        run: |
          npx vercel pull \
            --yes \
            --environment=production \
            --token "${{ secrets.VERCEL_TOKEN }}" \
            --project-id "${{ secrets.VERCEL_PROJECT_ID }}" \
            $([ -n "${{ secrets.VERCEL_TEAM_ID }}" ] && echo --scope "${{ secrets.VERCEL_TEAM_ID }}")

      - name: Build (production)
        run: npx vercel build --prod --token "${{ secrets.VERCEL_TOKEN }}"

      - name: Deploy (prebuilt -> prod)
        run: npx vercel deploy --prebuilt --prod --token "${{ secrets.VERCEL_TOKEN }}"
